services:
  db:
    build:
      context: .
      dockerfile: ./sql/Dockerfile.yaml
    image: vide-grenier-en-ligne-master_db_1
    restart: always
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.yaml
    image: vide-grenier-en-ligne-master_php_1
    restart: always
    ports:
      - 80:8000
