#FROM docker.io/composer:2.0.8 AS composer
FROM docker.io/composer:latest AS composer
FROM docker.io/php:7.4-apache

# Move our PHP file into the container
COPY . /usr/src/app/

# Make things easier if you shell in
WORKDIR /usr/src/app

# Our Apache will be running on port 80
EXPOSE 80

# Install the PDO MySQL extension so we can database
RUN docker-php-ext-install pdo_mysql

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Install nodejs and composer
RUN apt update && apt install -y nodejs npm git

# Build the app
RUN composer install
RUN npm install -g npm
RUN npm install
RUN npx node-sass style -o public/style --verbose

# Copy apache conf
COPY VideGrenierEnLigne.ApacheVirtualHost.conf /etc/apache2/sites-available/VideGrenierEnLigne.conf
RUN ln -s /etc/apache2/sites-available/VideGrenierEnLigne.conf /etc/apache2/sites-enabled/VideGrenierEnLigne.conf
RUN a2enmod rewrite

# Start apache2 http daemon
CMD ["apache2-foreground"]
