FROM docker.io/mariadb:10

# Set an insecure password
ENV MYSQL_ROOT_PASSWORD=example

# Copy over our SQL queries
COPY ./sql/*.sql /

# Startup MySQL and run the queries
CMD ["mysqld", "--init-file=/init.sql"]
